production:
  adapter: postgresql
  encoding: unicode
  database: runline_production
  localhost: 3000
  pool: 5

development:
  adapter: sqlite3
  encoding: unicode
  database: db/runline_development.sqlite3
  localhost: 3000
  host: localhost
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: db/runline_test.sqlite3
  localhost: 3000
  host: localhost
  pool: 5
